### ISSUE TITLE
Why dropping CocoaPods support?

### ISSUE THREAD

**Issue by bubski** [Zewo/URI#2]
As in the title. I'm using `Zewo` libs in a project on OS X. Currently, `SPM` is far from ready and `CocoaPods` (or `Carthage`) are still the best options to manage dependencies.
Is it because of `Swift 2.2` requirement? If so, what does strictly require `Swift 2.2` in `URI`?

**Comment by paulofaria** [comment]
We will try to fix this, but the problem is that SPM is not compatible with Xcode projects when you have lots of dependencies, specially if it is a C lib dependency.
